name: frontend deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: build
        run: npm install && npm run build
        env: 
          API_URL: ${{ secrets.STRAPI_API_URL}}
          GATSBY_ROOT_URL: ยง{{ secrets.GATSBY_ROOT_URL }}
      - name: Deploy with gh-pages 
        run: |
          git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/${PAGES_REPO}
          npx gh-pages -d public -u "github-actions-bot <support+actions@github.com>"
        env:
          API_URL: ${{ secrets.STRAPI_API_URL}}
          GATSBY_ROOT_URL: ยง{{ secrets.GATSBY_ROOT_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          PAGES_REPO: ${{ secrets.GH_PAGES_REPO }}